# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '190805001_i_firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 190805001_i_firebase

  pod 'Firebase/Analytics'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.3'

end
